### ISSUE TITLE
活動圖建議-楊珽郁

### ISSUE THREAD

**Issue by yurutung** [pacodeng/BaseProject#12]
起始點在哪裡需畫出
拍照須寫清楚，使用者利用你們的系統拍照?
自我檢討是使用者心理嗎? 還是有什麼需要輸入
繼續下個任務的話是否回到上方步驟，須繞回
什麼時候會結束，需有選擇
圓方框、方框 需照規定畫!

**Comment by Sabina-0219** [comment]
已更改

**Comment by Sabina-0219** [comment]
助教: 
以上更改有收到嗎?因為助教未回應，而且作業成績是更改前的

**Comment by yurutung** [comment]
抱歉抱歉 訊息太多被洗掉了 你的OK了喔 我在幫你更改成績~~  有空再看一下有沒有更正了
